name: etckeeper # you probably want to 'snapcraft register <name>'
version: "1.18.2" # just for humans, typically '1.2+git' or '1.3.2'
summary: etckeeper - tools to let /etc be stored in a git, mercurial, or bzr # 79 char long summary
description: |
  It hooks into apt (and other package managers) to automatically commit
  changes made to /etc during package upgrades. It tracks file metadata that
  revision control systems do not normally support, but that is important for
  /etc, such as the permissions of /etc/shadow. It's quite modular and
  configurable, while also being simple to use if you understand the basics of
  working with revision control.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  etckeeper:
    command: bin/etckeeper.wrapper
  git:
    command: git
  bzr:
    command: bzr
  hg:
    command: hg
  darcs:
    command: darcs

parts:
  etckeeper:
    plugin: dump
    source: .
    stage-packages:
      - etckeeper
    organize:
      scripts: bin

  git:
    plugin: nil
    stage-packages:
      - git

  bzr:
    plugin: nil
    stage-packages:
      - bzr

  hg:
    plugin: nil
    stage-packages:
      - mercurial

  darcs:
    plugin: nil
    stage-packages:
      - darcs
